# Generated by Django 3.0.6 on 2020-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
