# Generated by Django 3.0.6 on 2020-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0004_auto_20200524_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_attendee_count',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='private_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='private_group',
            field=models.BooleanField(default=False),
        ),
    ]
