# Generated by Django 3.0.6 on 2020-05-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0006_event_event_videochat_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member',
        ),
    ]
