# Generated by Django 3.0.6 on 2020-05-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0010_auto_20200526_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_category',
            field=models.CharField(choices=[('art', 'Arts'), ('film', 'Film'), ('mus', 'Music'), ('tech', 'Technology'), ('game', 'Games'), ('fit', 'Fitness'), ('lgbtq', 'LGBTQ'), ('pet', 'Pets'), ('photo', 'Photography'), ('book', 'Book Clubs'), ('fash', 'Fashion and Beauty'), ('lang', 'Languages'), ('relig', 'Religion'), ('biz', 'Business and Career'), ('sport', 'Sports'), ('yoga', 'Meditation and Yoga'), ('speak', 'Public Speaking'), ('soc', 'Socializing'), ('meet', 'Meeting New People'), ('polit', 'Politics'), ('hobb', 'Hobbies'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='activity_category',
            field=models.CharField(choices=[('art', 'Arts'), ('film', 'Film'), ('mus', 'Music'), ('tech', 'Technology'), ('game', 'Games'), ('fit', 'Fitness'), ('lgbtq', 'LGBTQ'), ('pet', 'Pets'), ('photo', 'Photography'), ('book', 'Book Clubs'), ('fash', 'Fashion and Beauty'), ('lang', 'Languages'), ('relig', 'Religion'), ('biz', 'Business and Career'), ('sport', 'Sports'), ('yoga', 'Meditation and Yoga'), ('speak', 'Public Speaking'), ('soc', 'Socializing'), ('meet', 'Meeting New People'), ('polit', 'Politics'), ('hobb', 'Hobbies'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yap.Language', verbose_name='Primary Language'),
        ),
    ]
