# Generated by Django 3.0.6 on 2020-05-28 14:49

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import storage_backends
import yap.models
import yap.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0011_auto_20200527_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=storage_backends.PrivateMediaStorage(), upload_to=yap.models.update_filename_event_avatar, validators=[yap.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=storage_backends.PrivateMediaStorage(), upload_to=yap.models.update_filename_group_avatar, validators=[yap.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=storage_backends.PrivateMediaStorage(), upload_to=yap.models.update_filename_profile_avatar, validators=[yap.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity_category',
            field=models.CharField(choices=[('', '-----'), ('art', 'Arts'), ('book', 'Book Clubs'), ('biz', 'Business and Career'), ('fash', 'Fashion and Beauty'), ('film', 'Film'), ('fit', 'Fitness'), ('game', 'Games'), ('hobb', 'Hobbies'), ('lang', 'Languages'), ('yoga', 'Meditation and Yoga'), ('meet', 'Meeting New People'), ('mus', 'Music'), ('pet', 'Pets'), ('photo', 'Photography'), ('polit', 'Politics'), ('speak', 'Public Speaking'), ('relig', 'Religion'), ('soc', 'Socializing'), ('sport', 'Sports'), ('tech', 'Technology'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='post_text',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='activity_category',
            field=models.CharField(choices=[('', '-----'), ('art', 'Arts'), ('book', 'Book Clubs'), ('biz', 'Business and Career'), ('fash', 'Fashion and Beauty'), ('film', 'Film'), ('fit', 'Fitness'), ('game', 'Games'), ('hobb', 'Hobbies'), ('lang', 'Languages'), ('yoga', 'Meditation and Yoga'), ('meet', 'Meeting New People'), ('mus', 'Music'), ('pet', 'Pets'), ('photo', 'Photography'), ('polit', 'Politics'), ('speak', 'Public Speaking'), ('relig', 'Religion'), ('soc', 'Socializing'), ('sport', 'Sports'), ('tech', 'Technology'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='language_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yap.Language', verbose_name='Primary Language'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='post_text',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Region / Province / State'),
        ),
    ]
