# Generated by Django 3.0.6 on 2020-05-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0013_auto_20200528_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activity_category',
            field=models.CharField(blank=True, choices=[('', '-----'), ('art', 'Arts'), ('book', 'Book Clubs'), ('biz', 'Business and Career'), ('fash', 'Fashion and Beauty'), ('film', 'Film'), ('fit', 'Fitness'), ('game', 'Games'), ('hobb', 'Hobbies'), ('lang', 'Languages'), ('yoga', 'Meditation and Yoga'), ('meet', 'Meeting New People'), ('mus', 'Music'), ('pet', 'Pets'), ('photo', 'Photography'), ('polit', 'Politics'), ('speak', 'Public Speaking'), ('relig', 'Religion'), ('soc', 'Socializing'), ('sport', 'Sports'), ('tech', 'Technology'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
