# Generated by Django 3.0.6 on 2020-05-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0014_auto_20200529_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='member_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yap.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yap.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendee',
        ),
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='attendees', through='yap.EventAttendance', to='yap.Profile'),
        ),
    ]
