# Generated by Django 3.0.6 on 2020-05-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0015_auto_20200529_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yap.Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yap.Profile')),
            ],
        ),
    ]
