# Generated by Django 3.0.6 on 2020-05-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0016_groupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members', through='yap.GroupMembership', to='yap.Profile'),
        ),
    ]
