# Generated by Django 3.0.6 on 2020-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0018_auto_20200530_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accept_sms',
            field=models.BooleanField(default=True),
        ),
    ]
