# Generated by Django 3.0.6 on 2020-05-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0019_auto_20200530_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_videochat_room_name',
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_videochat_room_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accept_email',
            field=models.BooleanField(default=True, verbose_name='Accept Email Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accept_sms',
            field=models.BooleanField(default=True, verbose_name='Accept SMS Notifications'),
        ),
    ]
