# Generated by Django 3.0.6 on 2020-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0020_auto_20200530_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_per_room',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='event',
            name='split_attendees_into_multiple_rooms',
            field=models.BooleanField(default=False),
        ),
    ]
