# Generated by Django 3.0.6 on 2020-05-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0021_auto_20200531_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='private_event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_videochat_room_base_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='split_attendees_into_multiple_rooms',
            field=models.BooleanField(default=True),
        ),
    ]
