# Generated by Django 3.0.6 on 2020-06-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0022_auto_20200531_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_per_room',
            field=models.IntegerField(blank=True, default=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='split_attendees_into_multiple_rooms',
            field=models.BooleanField(),
        ),
    ]
