# Generated by Django 3.0.6 on 2020-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0023_auto_20200602_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees_per_room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='split_attendees_into_multiple_rooms',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='maximum_attendee_count',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
