# Generated by Django 3.0.6 on 2020-06-02 19:45

from django.db import migrations, models
import imagekit.models.fields
import storage_backends
import yap.models
import yap.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0024_auto_20200602_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_jitsi',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=storage_backends.PrivateMediaStorage(), upload_to=yap.models.update_filename_event_avatar, validators=[yap.validators.validate_image_file_extension], verbose_name='Event Avatar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, default='', verbose_name='Event URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Event Name'),
        ),
    ]
