# Generated by Django 3.0.6 on 2020-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0026_event_reminder_email_sent_pre_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
