# Generated by Django 3.0.6 on 2020-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yap', '0027_auto_20200604_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='event_videochat_room_name',
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='reminder_email_sent_pre_event',
            field=models.BooleanField(default=False),
        ),
    ]
